apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-paiement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password_root
            - name: MYSQL_DATABASE
              value: paiement
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: db-paiement-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
